BEGIN TRANSACTION;

USE XYZ;

CREATE TABLE dbo.ContactInformation (
	Id INT IDENTITY(1, 1) NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	CellPhone NVARCHAR(20) NOT NULL
);

ALTER TABLE dbo.ContactInformation   
	ADD CONSTRAINT pk_ContactInformation PRIMARY KEY CLUSTERED(Id ASC);

CREATE TABLE dbo.Warehouse (
	Id INT IDENTITY(1, 1) NOT NULL
);

ALTER TABLE dbo.Warehouse   
	ADD CONSTRAINT pk_Warehouse PRIMARY KEY CLUSTERED(Id ASC);

CREATE TABLE dbo.Truck (
	Id INT IDENTITY(1, 1) NOT NULL,
	BrandName NVARCHAR (100) NOT NULL,
	RegistrationNumber NVARCHAR(100) NOT NULL,
	Payload DECIMAL NOT NULL,
	Volume DECIMAL NOT NULL,
	FuelConsumption DECIMAL NOT NULL,
);

ALTER TABLE dbo.Truck   
	ADD CONSTRAINT pk_Truck PRIMARY KEY CLUSTERED(Id ASC);

CREATE TABLE dbo.Driver (
	Id INT IDENTITY(1, 1) NOT NULL,
	TruckId INT NOT NULL
);

ALTER TABLE dbo.Driver   
	ADD CONSTRAINT pk_Driver PRIMARY KEY CLUSTERED(Id ASC),
		CONSTRAINT fk_Driver_Truck FOREIGN KEY (TruckId) REFERENCES dbo.Truck (Id) ON DELETE CASCADE;

CREATE TABLE dbo.[Route] (
	Id INT IDENTITY(1, 1) NOT NULL,
	OriginId INT NOT NULL,
	DestinationId INT NOT NULL,
	Distance DECIMAL NOT NULL
);

ALTER TABLE dbo.[Route]   
	ADD CONSTRAINT pk_Route PRIMARY KEY CLUSTERED(Id ASC),
		CONSTRAINT fk_Route_Origin FOREIGN KEY (OriginId) REFERENCES dbo.Warehouse (Id),
		CONSTRAINT fk_Route_Destination FOREIGN KEY (DestinationId) REFERENCES dbo.Warehouse (Id);

GO
CREATE TRIGGER [DELETE_Warehouse]
   ON dbo.Warehouse
   INSTEAD OF DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	DELETE FROM dbo.[Route] WHERE OriginId IN (SELECT Id FROM DELETED)
	DELETE FROM dbo.[Route] WHERE DestinationId IN (SELECT Id FROM DELETED)
END
GO

CREATE TABLE dbo.Shipment (
	Id INT IDENTITY(1, 1) NOT NULL,
	RouteId INT NOT NULL,
	DriverId INT NOT NULL,
	TruckId INT NOT NULL
);

ALTER TABLE dbo.Shipment   
	ADD CONSTRAINT pk_Shipment PRIMARY KEY CLUSTERED(Id ASC),
		CONSTRAINT fk_Shipment_Route FOREIGN KEY (RouteId) REFERENCES dbo.[Route] (Id) ON DELETE CASCADE,
		CONSTRAINT fk_Shipment_Driver FOREIGN KEY (DriverId) REFERENCES dbo.Driver (Id) ON DELETE CASCADE,
		CONSTRAINT fk_Shipment_Truck FOREIGN KEY (TruckId) REFERENCES dbo.Truck (Id) ON DELETE CASCADE;

CREATE TABLE dbo.Cargo (
	Id INT IDENTITY(1, 1) NOT NULL,
	[Weight] DECIMAL NOT NULL,
	Volume DECIMAL NOT NULL,
	CustomerId INT NOT NULL,
	RecipientId INT NOT NULL,
	RouteId INT NOT NULL
);

ALTER TABLE dbo.Cargo   
	ADD CONSTRAINT pk_Cargo PRIMARY KEY CLUSTERED(Id ASC),
		CONSTRAINT fk_Cargo_Customer FOREIGN KEY (CustomerId) REFERENCES dbo.ContactInformation (Id) ON DELETE CASCADE,
		CONSTRAINT fk_Cargo_Recipient FOREIGN KEY (RecipientId) REFERENCES dbo.ContactInformation (Id) ON DELETE CASCADE,
		CONSTRAINT fk_Cargo_Route FOREIGN KEY (RouteId) REFERENCES dbo.Route (Id) ON DELETE CASCADE;

COMMIT TRANSACTION;