USE Shipment_ML

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

GO

BEGIN TRANSACTION Transaction1
	SELECT *
	FROM dbo.[Route]
	WHERE Id = 2;

	WAITFOR DELAY '00:00:10';
COMMIT TRANSACTION Transaction1