USE Shipment_ML

/*First variant*/

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

GO

BEGIN TRANSACTION Transaction1
	SELECT *
	FROM dbo.[Route]
	WHERE Id = 2;

	WAITFOR DELAY '00:00:10';
COMMIT TRANSACTION Transaction1

/*Second variant*/

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

--GO

--BEGIN TRANSACTION Transaction1
--	SELECT *
--	FROM dbo.[Route]
--	WHERE Id = 2;

--	WAITFOR DELAY '00:00:10';
--COMMIT TRANSACTION Transaction1